CREATE TABLE DE_matches_hist AS 
WITH summed AS (
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2001'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2002'
UNION
-- HST and AST not available for seasons in grey below
--SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
--FROM 'DE_2003'
--UNION
--SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
--FROM 'DE_2004'
--UNION
--SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
--FROM 'DE_2005'
--UNION
--SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
--FROM 'DE_2006'
--UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2007'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2008'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2009'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2010'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2011'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2012'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2013'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2014'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2015'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2016'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2017'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM 'DE_2018')
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
FROM summed
;


 
 
  
  
  
 
 
 
 
  
  
  
  
  
  
  
  